# Generated by Django 4.2.4 on 2023-09-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_post_new_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_tags',
        ),
    ]
