# Generated by Django 4.2.4 on 2023-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_post_image_photo_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ManyToManyField(blank=True, to='blog.photo', verbose_name='Зображення'),
        ),
    ]
