# Generated by Django 4.2.4 on 2023-09-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_image_photo_image_post_photo_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_post',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_profile',
        ),
    ]
