# Generated by Django 4.2.4 on 2023-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_image_post_photo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/blog/profile')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
    ]
